sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  #- 5.6
  #- hhvm
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.9.1.1
    - MAGENTO_VERSION=magento-mirror-1.9.0.1
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.8.0.0
    - MAGENTO_VERSION=magento-mirror-1.7.0.2
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
script:
  # Code Style
  - php phpcs.phar --standard=./phpcs.xml --encoding=utf-8 --report-width=180 ./app ./shell
  # Unit Tests
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - travis@fabrizio-branca.de
    on_success: always
    on_failure: always
